# Generated by Django 4.1.7 on 2023-03-04 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_alter_task_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Created', 'Created'), ('In progress', 'Inprogress'), ('Finished', 'Finished'), ('Canceled', 'Canceled'), ('Expired', 'Expired')], default='Created', max_length=150),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(default='New Task', max_length=50),
        ),
    ]
