# Generated by Django 4.1.7 on 2023-03-04 13:47

from django.db import migrations, models
import task.models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('1', '3')], default=task.models.Task.TaskStatus['CREATED'], max_length=150),
        ),
    ]
